# Generated by Anaconda 37.12.6
# Generated by pykickstart v3.47
#version=F37
# Use graphical install
graphical
# License agreement
eula --agreed

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us','ru' --switch='grp:alt_shift_toggle','grp:win_space_toggle'
# System language
lang en_US.UTF-8

# Use CDROM installation media
cdrom

%packages
@^server-minimal-environment

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.7.1
ignoredisk --only-use=sda
# Partition clearing information
clearpart --none --initlabel
# Disk partitioning information
part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
part swap --fstype="swap" --ondisk=sda --size=12288
part pv.1267 --fstype="lvmpv" --ondisk=sda --size=37286 --encrypted --luks-version=luks2
part /boot --fstype="ext4" --ondisk=sda --size=1024
volgroup vg-main --pesize=4096 pv.1267
logvol / --fstype="ext4" --size=16800 --name=root --vgname=vg-main
logvol /home --fstype="ext4" --size=10240 --name=home --vgname=vg-main
logvol /var --fstype="ext4" --size=10240 --name=var --vgname=vg-main

# System timezone
timezone Europe/Moscow --utc

# Root password
rootpw --iscrypted $y$j9T$quHbq6PxsTcqguQiwb89tyQt$x4eqnRYSbBQCoCmBxf7/U9T0LYQDhRH4lxLa0qdDQw5
user --groups=wheel --name=neophyte --password=$y$j9T$fK5xdV2yCiGljuexttFnibIP$YCPb4ZLCLyL.5pofjkXDFgbGgYqLIC/ruK3Y8Q7RAoB --iscrypted --gecos="neophyte"
